---
title: "Resume"
toc: false
resources:
  - files/Rankin_Lindsay_Resume_2026_short.pdf
---

## Short Resume

```{=html}
<object data="files/Rankin_Lindsay_Resume_2026_short.pdf" type="application/pdf" width="80%" height="80%" style="min-height:100vh;">
    <p>It appears you don't have a PDF plugin for this browser.
    No biggie... you can <a href="files/Rankin_Lindsay_Resume_2026_short.pdf">click here to
    download the PDF file.</a></p>
</object>
```

# Further Details (aka a Long Resume)

## Freelance Work

The statistics and quantitative research focus of my PhD allowed me to build a freelance career in research and data analysis/statistics.\
In the past several years, I have expanded into data science, particularly by developing R coding skills.

My freelance work can be quite varied, but I can categorize it into roughly the following four buckets and provide some examples or details:

::: {.callout-note collapse="true"}
## Reviews
I have many clients through personal referrals, but I can also point to a couple of profiles for reviews:\

  - ["Top Rated Plus" and 100% Job Success badges on Upwork (across all four buckets)](https://www.upwork.com/freelancers/~0116bd0d723f5d3e8b)\
  - [4.9/5.0 rating from 2500+ reviews on Wyzant (across buckets 3 and 4)](https://www.wyzant.com/Tutors/StatisticsWithLindsay)\
:::

#### 1. Data Science

In an ongoing contract role with an HR/leadership consultancy, I am a part of the small analytics group within a fully remote team.\

  - We develop R code including creating and maintaining custom R packages to automate the process of integrating a data pipeline from survey responses (some light SQL calls to a data warehouse), cleaning and calculations, creating ggplot2 visuals, inserting images and content into prepared templates (some light Python debugging) to produce batches of custom reports.\
  - Early on, we implemented Github usage for version control and collaboration as projects scaled in complexity.\
  - More recently, we used the R package plumber to turn our report production R code into an API endpoint with an AWS VM to allow ongoing, on-demand production rather than batch runs. During this transition, I often took on the role of as a communication bridge for a cross-functional team. 

::: {.callout-note collapse="true"}
## Data Science performance reviews
I can highlight some ownership/manager reviews ([displayed under the "In Progress" tab](https://www.upwork.com/freelancers/~0116bd0d723f5d3e8b)).

"Lindsay is amazingly intelligent, skilled, and detailed-oriented. She is a skilled data scientist, but just as important [is] her ability to collaborate with team members and the ownership she takes with her deliverables to make sure that she gets the job done right. We love working with her and hope to continue doing so across many projects."

"Lindsay has been a pleasure to work with. She is exceptionally detail oriented and diligent, asking lots of good questions that help to ensure that the work gets done right the first time."
::: 

#### 2. Data Analysis / Research Projects

I am brought in at various stages of research projects: Sometimes during initial conception and development, often after data has already been collected and is ready for analysis and reporting. I work with business, nonprofit organizations, and academics. 

Example projects: 

  - Analysis of a user survey to advise new product development, including clustering/segmentation of clients
  - Questionnaire and survey development, survey programming, and data analysis of novel measurement scales to track client progress for a self-help influencer
  - Comparing rates of injury from motorcycle accidents by areas with (and without) interventions in a developing nation for a nonprofit

#### 3. Project Coaching / Consulting

I work with data analyst professionals to support their development of statistical testing/data analysis and R coding skills, often by coaching/consulting with them as they work through projects for their job.

I also do a lot of what I broadly call *Dissertation Coaching* or *Academic Research Coaching*. \
The distinction between these and what I above called *Data Analysis / Research Projects* is that I will often serve as support as the client works through the project, rather than doing the work myself. I serve as more involved, on-demand advisor or statistics consultant. This can also be at any step of the process:\

  - During the initial design phase of forming research questions and hypotheses, refining a study design, deciding on measurements, planning the analyses. Also general approaches to meeting potentially competing expectations of dissertation committee members, and broadly navigating the defense process \
  - After they have collected their data (or obtained secondary data) and are unsure of how to analyze it or how to implement an analysis plan. In addition to the statistics details, I help them to approach this in a systematic, organized manner\
  - During analysis when they find data does not meet assumptions of a planned analysis type and are unsure how to proceed\
  - After analyses when they struggle to figure out how to organize and communicate their results in written (and occasionally verbal/presentation) form\
  
#### 4. Tutoring

I tutor graduate and undergraduate students in statistics, research, and R coding.

::: {style="margin-left: 2em;"}
Common statistics topics include frequentist approaches, hypothesis testing and conceptual understandings underlying sampling distributions and p values, regression / general linear model frameworks (i.e., ANOVAs, t-tests), psychometric considerations (i.e., factor analyses, reliability)
:::

## Academic Publications

#### Journal articles
Rankin, L. E., Jost, J. T., & Wakslak, C. J. (2009). System justification and the meaning of life: Are the existential benefits of ideology distributed unequally across racial groups?. *Social Justice Research*, 22(2), 312-333.

Rankin, L. E., & Tyler, T. R. (2009). Justice and cooperation. *Netherlands Journal of Psychology*, 65(4), 146-154.

Rankin, L. E., & Eagly, A. H. (2008). Is his heroism hailed and hers hidden? Women, men, and the social construction of heroism. *Psychology of Women Quarterly*, 32(4), 414-422.

#### Book chapter co-author
Tyler, T. R., & Rankin, L. E. (2012). Public attitudes and punitive policies. In J. A. Dvoskin, J. L. Skeem, R. W. Novaco, & K. S. Douglas (Eds.), *Using social science to reduce violent offending* (pp. 103–123). Oxford University Press.

## Online Courses / Self-Teaching Tracks
Some of the courses I have completed: 

::: {style="margin-left: 2em; font-size: 0.85em;"}

DataCamp: Data Analyst with Python track\
36 hour career track

DataCamp: SQL Fundamentals track\
21 hour skills track

Coursera: An Introduction to Interactive Programming in Python (Parts 1 & 2)\
MOOC from Rice University

Coursera: Machine Learning\
MOOC from Stanford

DataCamp: Statistical Inference with R track

DataCamp: Statistics Fundamentals with R track

DataCamp: Tidyverse Fundamentals with R track

edX: Introduction to Computer Science and Programming Using Python\
MOOC from MITx

edX: Sabermetrics 101: Introduction to Baseball Analytics using R and SQL\
MOOC from Boston U

edx: The Analytics Edge using R\
MOOC from MITx
::: 